🌟Exercise 1: Introduction to Data Analysis (Easy)

What is data analysis?
   _Data analysis is collecting, "interrogating" and analysing data to find useful informations for a specific purpose
Why is data analysis important in modern contexts?
    _Data analysis is important in modern contexts because it can significantly helps to reach an objective.
List and describe three areas where data analysis is applied today.
    _Business, HealthCare, Public Policy.

🌟Exercise 2: Dataset Loading and Initial Analysis and 🌟Exercise 3: Identifying Data Types

In [2]:
import pandas as pd

Load the dataset into Jupyter or Google Colab.

In [ ]:
Mental_Health= pd.read_csv('Mental health Depression disorder Data.csv', index_col=0, low_memory=False)
Time_Americans= pd.read_csv('Time Americans Spend Sleeping.csv', index_col=0)
crx = pd.read_csv('crx.csv')
clean_dataset = pd.read_csv('clean_dataset.csv')

Display the first few rows and Provide a brief dataset description.

In [14]:

Time_Americans.head()

,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
index,,,,,,,,
0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both

In this dataset, 
        Qualitative Columns are: Period, Activity, Sex, Types of days, Age Group because they are non-numerical datas.
        
        Quantitative Colums are: Year, Avg per day sleeping.

This is a file showing the Average American's Time Sleeping

In [15]:
Mental_Health.head()

,Entity,Code,Year,Schizophrenia (%),Bipolar disorder (%),Eating disorders (%),Anxiety disorders (%),Drug use disorders (%),Depression (%),Alcohol use disorders (%)
index,,,,,,,,,,
0,Afghanistan,AFG,1990,0.16056,0.697779,0.101855,4.828830,1.677082,4.071831,0.672404
1,Afghanistan,AFG,1991,0.160312,0.697961,0.099313,4.829740,1.684746,4.079531,0.671768
2,Afghanistan,AFG,1992,0.160135,0.698107,0.096692,4.831108,1.694334,4.088358,0.670644
3,Afghanistan,AFG,1993,0.160037,0.698257,0.094336,4.830864,1.705320,4.096190,0.669738
4,Afghanistan,AFG,1994,0.160022,0.698469,0.092439,4.829423,1.716069,4.099582,0.669260

This is a file showing world mental and physical disorders datas.

The qualitative columns are: Entity  and Code because they are strings.
All other columns are quantitative because they are numerical.

In [16]:
crx.head()

   b  30.83      0  u  g  w  v  1.25  t t.1  01  f g.1  00202  0.1  +
0  a  58.67  4.460  u  g  q  h  3.04  t   t   6  f   g  00043  560  +
1  a  24.50  0.500  u  g  q  h  1.50  t   f   0  f   g  00280  824  +
2  b  27.83  1.540  u  g  w  v  3.75  t   t   5  t   g  00100    3  +
3  b  20.17  5.625  u  g  w  v  1.71  t   f   0  f   s  00120    0  +
4  b  32.08  4.000  u  g  m  v  2.50  t   f   0  t   g  00360    0  +

In [17]:
clean_dataset.head()

,Gender,Age,Debt,Married,BankCustomer,Industry,Ethnicity,YearsEmployed,PriorDefault,Employed,CreditScore,DriversLicense,Citizen,ZipCode,Income,Approved
0,1,30.83,0.000,1,1,Industrials,White,1.25,1,1,1,0,ByBirth,202,0,1
1,0,58.67,4.460,1,1,Materials,Black,3.04,1,1,6,0,ByBirth,43,560,1
2,0,24.50,0.500,1,1,Materials,Black,1.50,1,0,0,0,ByBirth,280,824,1
3,1,27.83,1.540,1,1,Industrials,White,3.75,1,1,5,1,ByBirth,100,3,1
4,1,20.17,5.625,1,1,Industrials,White,1.71,1,0,0,0,ByOtherMeans,120,0,1

Quantitative columns are all numerical columns except Married and Approved because they represent a statut.
All other columns are qualitative

This is a file showing Bank Approvals

🌟Exercise 4: Exploring Data Types

In [ ]:
iris = pd.read_csv('Iris.csv')
iris.head()

   Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

Id, SepalLength, SepalWidthCm and PetalWitdthcm are quantitative because because they are numerical.
Species is qualitative because it's text, it's a label

🌟Exercise 5: Basic Observation Skills in Data Analysis

In [21]:
Time_Americans

,Year,Period,Avg hrs per day sleeping,Standard Error,Type of Days,Age Group,Activity,Sex
index,,,,,,,,
0,2003,Annual,8.57,0.018,All days,15 years and over,Sleeping,Both
1,2004,Annual,8.55,0.026,All days,15 years and over,Sleeping,Both
2,2005,Annual,8.62,0.023,All days,15 years and over,Sleeping,Both
3,2006,Annual,8.63,0.024,All days,15 years and over,Sleeping,Both
4,2007,Annual,8.57,0.024,All days,15 years and over,Sleeping,Both
...,...,...,...,...,...,...,...,...
940,2013,Annual,8.83,0.085,Nonholiday weekdays,65 years and over,Sleeping,Women
941,2014,Annual,8.98,0.086,Nonholiday weekdays,65 years and over,Sleeping,Women
942,2015,Annual,8.83,0.074,Nonholiday weekdays,65 years and over,Sleeping,Women
943,2016,Annual,8.92,0.071,Nonholiday weekdays,65 years and over,Sleeping,Women
944,2017,Annual,8.81,0.091,Nonholiday weekdays,65 years and over,Sleeping,Women

We can for instance use:
   _Colums Sex and Avg hrs per day to know which sex sleep more.
   _Columns Year and Avg hrs per day pto know if people sleep less now or not

🌟 Exercise 6: Identifying Data Types

A company’s financial reports stored in an Excel file: Structured Data
Photographs uploaded to a social media platform: Unstructured Data
A collection of news articles on a website: Structured Data
Inventory data in a relational database: Structured Data
Recorded interviews from a market research study: Unstructured Data

🌟 Exercise 7: Transformation Exercise

For each of the following unstructured data sources, propose a method to convert it into structured data. Explain your reasoning.

A series of blog posts about travel experiences: We could gather the posts based on the destinations.
Audio recordings of customer service calls: We could gather the audio based on the recording hour or the purpose.
Handwritten notes from a brainstorming session: We could gather the notes bases on who wrote it.
A video tutorial on cooking: We could Separate the video by sections. Example: peelingd of fruits is from...to...

🌟 Exercise 8 : Import a file from Kaggle

In [22]:
train = pd.read_csv('train.csv')
train.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

🌟 Exercise 9 : Export a dataframe to excel format and JSON format.

In [33]:
simple_dataframe = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 32],
    'City': ['New York', 'Paris', 'Berlin', 'London']
}
df = pd.DataFrame(simple_dataframe)
df

df.to_excel('simple_data.xlsx', index=False)
df.to_json('simple_dataframe.json')

🌟 Exercise 10: Reading JSON Data

In [35]:
json_data = pd.read_json('posts.json')
json_data.head()

,userId,id,title,body
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...